### ISSUE TITLE
Mono build is broken but Travis reports success

### ISSUE THREAD

**Issue by jonorossi** [castleproject/Core#282]
The build was broken by #279, but looks like build.sh returns 0 on failure.

```
e/travis/build/castleproject/Core/src/Castle.Core/bin/Release/net45/Castle.Core.dll
e/travis/build/castleproject/Core/src/Castle.Services.Logging.SerilogIntegration/bin/Release/net45/Castle.Services.Logging.SerilogIntegration.dll
e/travis/build/castleproject/Core/src/Castle.Services.Logging.log4netIntegration/bin/Release/net45/Castle.Services.Logging.log4netIntegration.dll
e/travis/build/castleproject/Core/src/Castle.Services.Logging.NLogIntegration/bin/Release/net45/Castle.Services.Logging.NLogIntegration.dll
CustomModifiersTestCase.cs(128,9): error CS0117: 'BasePEVerifyTestCase' does not contain a definition for 'RunPEVerifyOnGeneratedAssembly' [/home/travis/build/castleproject/Core/src/Castle.Core.Tests/Castle.Core.Tests.csproj]
Build FAILED.
CustomModifiersTestCase.cs(128,9): error CS0117: 'BasePEVerifyTestCase' does not contain a definition for 'RunPEVerifyOnGeneratedAssembly' [/home/travis/build/castleproject/Core/src/Castle.Core.Tests/Castle.Core.Tests.csproj]
    0 Warning(s)
    1 Error(s)
Time Elapsed 00:00:15.73
Running NET461 Tests
--------------------
./build.sh: line 52: ./src/Castle.Core.Tests/bin/Release/net461/Castle.Core.Tests.exe: No such file or directory
---------------------------
Running NETCOREAPP1.1 Tests
---------------------------
No executable found matching command "dotnet-./src/Castle.Core.Tests/bin/Release/netcoreapp1.1/Castle.Core.Tests.dll"
grep: NetCoreClrTestResults.xml: No such file or directory
grep: DesktopClrTestResults.xml: No such file or directory
The command "./build.sh" exited with 0.
Done. Your build exited with 0.
```
(https://travis-ci.org/castleproject/Core/builds/248289034)

/cc @fir3pho3nixx @stakx

**Comment by jonorossi** [comment]
@stakx looks like all the new unit tests fail on Mono too with something like this:

```
1) Failed : Castle.DynamicProxy.Tests.CustomModifiersTestCase.ReflectionReturnsCorrectModoptOnParamTypeForGeneratedType("Bar_AsModoptOnParamType")
  Expected is <System.Linq.Enumerable+<ReverseIterator>c__Iterator14`1[System.Type]>, actual is <System.Type[0]>
  Values differ at index [0]
at NUnit.Framework.CollectionAssert.AreEqual (System.Collections.IEnumerable expected, System.Collections.IEnumerable actual, System.String message, System.Object[] args) [0x00007] in <a136915bdafc4f7db46d0b0a906d5367>:0
at NUnit.Framework.CollectionAssert.AreEqual (System.Collections.IEnumerable expected, System.Collections.IEnumerable actual) [0x00000] in <a136915bdafc4f7db46d0b0a906d5367>:0
at Castle.DynamicProxy.Tests.CustomModifiersTestCase.ReflectionReturnsCorrectModoptOnParamTypeForGeneratedType (System.String typeName) [0x0007d] in <7c1f1dfc9a0a4c998d2f46b9da70e260>:0
```
(https://travis-ci.org/castleproject/Core/builds/248656337)

**Comment by stakx** [comment]
@jonorossi: That's very interesting. This could mean that the modopt bug I fixed was never present on Mono to begin with, only on Microsoft's CLR. I'll install Mono and run some tests.

**Comment by jonorossi** [comment]
I've fixed `build.sh` to return non-zero if compilation fails in #282.

**Comment by fir3pho3nixx** [comment]
Will pick this one up over the weekend.

**Comment by stakx** [comment]
https://github.com/stakx/Core/commit/d5c29bf3471f12bdd64c241e7384e47446e9769e would possibly fix the failing tests on Mono, but I haven't actually verified the claims made in those comments, so no PR just yet.

**Comment by jonorossi** [comment]
Closing this as we've fixed the Linux build script problems, I've reopened #277.

**Comment by jonorossi** [comment]
> stakx/Core@d5c29bf would possibly fix the failing tests on Mono, but I haven't actually verified the claims made in those comments, so no PR just yet.

@stakx we can't (and don't want to) use `__MonoCS__` in any library code as we don't ship a separate Mono build.
